name: C/C++ CI for GCL2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: dump env
      run: env && gcc --version
    - name: make me
      run: make clean && make && make dist

